// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxrshlzotkyptnaxunmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4cnNobHpvdGt5cHRuYXh1bm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTA5MTQsImV4cCI6MjA3ODA4NjkxNH0.PkHaeYsnMb4NGjb8H4T3eJS5q1wAZlyKEpzFm2-jagA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});